### ISSUE TITLE
Params always emty

### ISSUE THREAD

**Issue by itschn** [sinisterchipmunk/bot-away#2]
Running rails 3.1.1

Parameters always empty, wich leads to unexpected redirects.
We have a multilanguage app and trying to set the locale through params.

Thanx

**Comment by itschn** [comment]
seems like something with request.parameters is broken

**Comment by sinisterchipmunk** [comment]
I am able to reproduce this issue. Interestingly, it looks like it is an issue specifically with GET requests. POST worked as expected, at least in my test app.

Now writing a failing test case.

**Comment by sinisterchipmunk** [comment]
One note -- you mentioned you are managing localization with extra params. If you continue to have problems, try adding the name of the extra param key(s) to an initializer like so:

```
# config/initializers/bot-away.rb
BotAway.accepts_unfiltered_params "name_of_localization_param"
```

This will cause BotAway to always consider the named param to be valid, effectively disabling BotAway for that param.
